#!/usr/bin/env Rscript
# =============================================================================
# make_fig_sample_efficiency.R
#
# Figure: sample efficiency of BATON on the binary Simon benchmark
#         (p0 = 0.20, p1 = 0.40, type I <= 0.10, power >= 0.80)
#
# X-axis: cumulative design evaluations
# Y-axis: best FEASIBLE expected null sample size E_0[N] found so far
#
# -----------------------------------------------------------------------------
# PROVENANCE: every plotted value is a stored evaluation. Nothing is simulated,
# smoothed, imputed or synthesized by this script.
# -----------------------------------------------------------------------------
#
# Series 1 - BATON trajectories (10 runs, spaghetti + min-max band + median)
#   FILE: ~/Downloads/adaptive-trial-bo-paper/results/validation/
#         reproducibility_trajectories.csv   (2,637 rows; cols iter,
#         best_feasible_EN, run, seed)
#   GENERATED BY: scripts/run_reproducibility_analysis.R, which runs
#         BATON::bo_calibrate() 10 times with seeds 2025:2034 and stores
#         cummin(objective over feasible rows) against row_number() of
#         bo_fit$history. So `iter` IS the cumulative design-evaluation index
#         and `best_feasible_EN` IS a real best-so-far curve. Verified
#         monotone non-increasing within every run.
#
# Series 2 - the LHS / space-filling baseline (evaluations 1-100 of the SAME runs)
#   Same file. run_reproducibility_analysis.R calls bo_calibrate() with
#   n_init = 100, q = 4, budget = 300, initial_history = NULL (warm start
#   explicitly disabled). BATON evaluates a Latin hypercube initial design of
#   n_init points FIRST and only then enters the GP-guided acquisition loop
#   (BATON/R/bo_calibrate.R: `initial_design <- lhs_design(n_init, bounds, ...)`).
#   Therefore evaluations 1-100 are a space-filling random search over the
#   SAME box, the SAME simulator and the SAME fidelities as the BO phase, and
#   evaluations 101+ are BO-guided. This is the only baseline in the repository
#   that is commensurable with the BATON series (see EXCLUSIONS below).
#   Consistency check: all 10 stored converged_iter values are divisible by
#   q = 4, consistent with a 100-point init plus batches of 4.
#
# Run endpoints (terminal markers)
#   FILE: results/validation/reproducibility_10runs.csv (10 rows)
#   Columns converged_iter and EN_null. EN_null there is an INDEPENDENT
#   re-validation of each run's chosen design at 10,000 MC replications with a
#   different seed (seed + 1000). It reproduces each trajectory's final value
#   to 0.000000 for all 10 runs, which is expected because
#   scripts/sim_fun_binary.R computes operating characteristics by EXACT
#   binomial calculation (Monte Carlo is used only for hetGP variance
#   estimates). The plotted y-values therefore carry no Monte Carlo selection
#   ("winner's curse") bias.
#
# Reference lines - Simon (1989) exact two-stage designs
#   clinfun::ph2simon(0.20, 0.40, 0.10, 0.20):
#     optimal          r1=2 n1=12 r=7 n=25  EN(p0) = 17.74151
#     next admissible  r1=2 n1=11 r=8 n=29  EN(p0) = 17.88677
#   These are exact analytic values, not simulation output. 8/10 BATON runs
#   terminate exactly on the first, 2/10 exactly on the second. The second
#   line is drawn so the floor of the band is explained rather than left as an
#   unexplained gap.
#
# -----------------------------------------------------------------------------
# EXCLUSIONS - baselines deliberately NOT plotted, and why
# -----------------------------------------------------------------------------
# results/validation/random_search_2000.csv (2,000 rows, real per-evaluation
#   data, `config` column IS the evaluation order) is NOT plotted. It is not
#   commensurable with the BATON series on a shared y-axis:
#   (a) DIFFERENT DESIGN CLASS. It was generated by run_random_search_analysis.R
#       through evolveTrial::run_simulation_binary() with an interim EFFICACY
#       stopping rule in addition to futility. For 1,999 of its 2,000 rows the
#       stored EN_null is strictly below n1 + (1 - PET_null) * (n_total - n1),
#       the value futility-only stopping would give (median shortfall 1.15
#       patients), confirming the extra stopping mode. BATON's simulator
#       (scripts/sim_fun_binary.R) is futility-only, matching Simon's
#       structure. E_0[N] below 17.74 is therefore legitimately attainable in
#       the random-search design class, so Simon's optimum is not its floor
#       and the two curves do not measure the same quantity.
#   (b) DIFFERENT SEARCH BOX. random search fut_prob in [0.50, 0.95] and
#       n1 in [8, 20]; BATON fut in [0.01, 0.30] and n1 in [8, 25].
#   (c) NOISE ASYMMETRY. Random search evaluated each config once at 2,000 MC
#       replications and its selected point was never re-validated. Its best
#       feasible design (config 89: EN 17.75, power 0.8085, type I 0.0900) sits
#       about 1 MC standard error inside both constraint boundaries, as do the
#       next several; that best-so-far value is a selection minimum over 2,000
#       noisy estimates and is optimistically biased.
# results/validation/grid_exhaustive_4param.csv - all 400 rows have NA
#   EN/power/type1 and zero feasible. Dead file.
# results/validation/bobyqa_history.csv - 125 rows, zero feasible, and a
#   different (survival, event-driven) design space.
# results/validation/ablation_study.csv - endpoints only, no trajectories.
#
# -----------------------------------------------------------------------------
# PLOTTING CONVENTIONS (disclosed)
# -----------------------------------------------------------------------------
# * Best-so-far is a step function. Each run is expanded onto the common grid
#   1:300 by last-observation-carried-forward. A run is undefined before its
#   first FEASIBLE evaluation (runs first become feasible at evaluations 1-4),
#   and those leading cells are left NA rather than filled.
# * Runs early-stop at 232-300 evaluations. Past its own stopping point a run's
#   final value is carried forward (it is that run's reported answer). The
#   actual stopping points are marked with dots so this is visible.
# * The y-axis is clipped at 26. This hides 20 of 2,989 plotted cells, all at
#   evaluation <= 11 (the first feasible draw of a few runs, up to 33.2).
#
# INPUT : ~/Downloads/adaptive-trial-bo-paper/results/validation/
#           reproducibility_trajectories.csv, reproducibility_10runs.csv
# OUTPUT: images/fig_sample_efficiency.png  (9 x 4 in, 300 DPI)
# =============================================================================

suppressPackageStartupMessages(library(ggplot2))

# ---- paths ------------------------------------------------------------------
REPO    <- path.expand(Sys.getenv("BATON_PAPER_DIR", "~/Downloads/adaptive-trial-bo-paper"))  # manuscript repo (results/validation/*)
OUT_DIR <- file.path(dirname(normalizePath(sub("^--file=", "", grep("^--file=", commandArgs(FALSE), value = TRUE)[1]), mustWork = FALSE)), "images")  # <deck dir>/images
if (!dir.exists(OUT_DIR)) OUT_DIR <- "images"
TRAJ    <- file.path(REPO, "results/validation/reproducibility_trajectories.csv")
ENDS    <- file.path(REPO, "results/validation/reproducibility_10runs.csv")

stopifnot(file.exists(TRAJ), file.exists(ENDS))
dir.create(OUT_DIR, recursive = TRUE, showWarnings = FALSE)

# ---- constants --------------------------------------------------------------
N_INIT        <- 100        # LHS initial design size (run_reproducibility_analysis.R)
BUDGET        <- 300        # BO budget per run
SIMON_OPT     <- 17.74151   # clinfun::ph2simon(.20,.40,.10,.20) optimal EN(p0)
SIMON_ADMIS2  <- 17.88677   # next admissible design EN(p0)
Y_CLIP        <- 26

# ---- palette ----------------------------------------------------------------
navy          <- "#13294B"
carolina      <- "#4B9CD3"
carolina_deep <- "#2E6A9F"
graphite      <- "#5B6670"

# ---- load -------------------------------------------------------------------
traj <- read.csv(TRAJ, stringsAsFactors = FALSE)
ends <- read.csv(ENDS, stringsAsFactors = FALSE)

# integrity checks: the curve must already be a best-so-far (non-increasing)
for (r in split(traj, traj$run)) {
  stopifnot(all(diff(r$best_feasible_EN) <= 1e-9))
}
stopifnot(nrow(ends) == 10, all(ends$feasible))

# ---- expand each run onto the common evaluation grid via LOCF ---------------
grid <- do.call(rbind, lapply(split(traj, traj$run), function(d) {
  y <- approx(d$iter, d$best_feasible_EN, xout = seq_len(BUDGET),
              method = "constant", f = 0, rule = 2)$y
  y[seq_len(BUDGET) < min(d$iter)] <- NA   # undefined before first feasible point
  data.frame(iter = seq_len(BUDGET), run = d$run[1], en = y)
}))

# ---- min-max band and median across the 10 runs -----------------------------
band <- do.call(rbind, lapply(split(grid, grid$iter), function(d) {
  v <- d$en[!is.na(d$en)]
  if (!length(v)) return(NULL)
  data.frame(iter = d$iter[1], lo = min(v), hi = max(v), md = median(v))
}))

# ---- endpoints --------------------------------------------------------------
endpts <- data.frame(iter = ends$converged_iter, en = ends$EN_null)

# ---- summary numbers used in the on-figure annotations ----------------------
at_init  <- grid$en[grid$iter == N_INIT]
n_exact  <- sum(abs(ends$EN_null - SIMON_OPT)    < 1e-4)
n_admis2 <- sum(abs(ends$EN_null - SIMON_ADMIS2) < 1e-4)
lab_init <- sprintf(
  "Space-filling initial design\nplateaus at %.1f patients",
  median(at_init))
lab_bo <- sprintf(
  "Model-guided phase: %d of 10 runs land\nexactly on Simon\u2019s optimal design;\n%d land 0.15 patients away",
  n_exact, n_admis2)

cat(sprintf("LHS phase (eval %d): median %.2f, range [%.2f, %.2f]\n",
            N_INIT, median(at_init), min(at_init), max(at_init)))
cat(sprintf("Final: %d/10 at %.5f, %d/10 at %.5f\n",
            n_exact, SIMON_OPT, n_admis2, SIMON_ADMIS2))

# ---- theme ------------------------------------------------------------------
theme_deck <- theme_minimal(base_size = 14) +
  theme(
    panel.grid.minor = element_blank(),
    panel.grid.major = element_line(color = "#EDF0F2"),
    axis.title       = element_text(face = "bold", color = navy, size = 16),
    axis.text        = element_text(color = graphite, size = 16),
    plot.margin      = margin(8, 14, 8, 8)
  )

# ---- plot -------------------------------------------------------------------
p <- ggplot() +
  # phase divider: end of the space-filling initial design
  geom_vline(xintercept = N_INIT, linetype = "dashed",
             color = graphite, linewidth = 0.5) +
  # exact reference designs
  geom_hline(yintercept = SIMON_ADMIS2, linetype = "dotted",
             color = graphite, linewidth = 0.6) +
  geom_hline(yintercept = SIMON_OPT, linetype = "dashed",
             color = navy, linewidth = 0.7) +
  # min-max band across the 10 runs
  geom_ribbon(data = band, aes(x = iter, ymin = lo, ymax = hi),
              fill = carolina, alpha = 0.18) +
  # individual run trajectories
  geom_line(data = grid[!is.na(grid$en), ],
            aes(x = iter, y = en, group = run),
            color = carolina_deep, alpha = 0.45, linewidth = 0.4) +
  # median across runs
  geom_line(data = band, aes(x = iter, y = md),
            color = navy, linewidth = 0.9) +
  # where each run actually stopped
  geom_point(data = endpts, aes(x = iter, y = en),
             color = navy, fill = "white", shape = 21,
             size = 1.6, stroke = 0.7) +
  # on-figure labels in place of a legend
  # (geom_label rather than annotate(): annotate() silently drops the border control,
  #  which would leave a visible border box on every label)
  geom_label(data = data.frame(x = 34, y = 25.0, lab = lab_init),
             aes(x = x, y = y, label = lab), inherit.aes = FALSE,
             hjust = 0, vjust = 1, size = 4.7, color = graphite,
             fill = "white", linewidth = 0, lineheight = 1.05) +
  geom_label(data = data.frame(x = 297, y = 25.0, lab = lab_bo),
             aes(x = x, y = y, label = lab), inherit.aes = FALSE,
             hjust = 1, vjust = 1, size = 4.7, color = carolina_deep,
             fill = "white", linewidth = 0, lineheight = 1.05) +
  geom_label(data = data.frame(
               x = 186, y = 17.42,
               lab = sprintf("Simon exact optimum %.2f", SIMON_OPT)),
             aes(x = x, y = y, label = lab), inherit.aes = FALSE,
             hjust = 0.5, vjust = 0.5, size = 4.7, color = navy,
             fill = "white", linewidth = 0) +
  scale_x_continuous(breaks = c(1, 50, 100, 150, 200, 250, 300),
                     expand = expansion(mult = c(0.012, 0.012))) +
  scale_y_continuous(breaks = seq(18, 26, by = 2)) +
  coord_cartesian(xlim = c(1, BUDGET), ylim = c(17.3, Y_CLIP)) +
  labs(
    x = "Cumulative design evaluations",
    y = "Expected patients if inactive\n(best feasible so far)"
  ) +
  theme_deck

ggsave(file.path(OUT_DIR, "fig_sample_efficiency.png"), p,
       width = 10, height = 4.4, dpi = 300)

cat("Wrote: ", file.path(OUT_DIR, "fig_sample_efficiency.png"), "\n", sep = "")
